# user specifiable configurations go here

steam-community-market-tracker:
  misc:
    currency: 3
    currency-name: EUR
  limits:
    market-item-search: 15s
    market-item-price-search: 4s
    market-inventory-search: 10s
  app-search:
    on-startup: false
    on-cron: false
    cron: 0 0 0 * * * # at midnight
    track-by-default: false
    disable-tracking-on-empty-response: true
    delete-not-found-entities: false
  item-search:
    on-startup: false
    on-cron: false
    cron: 0 0 */1 * * * # every hour
    no-update-before: 24h
    track-by-default: false
    disable-tracking-on-empty-response: true
    delete-no-longer-found: false
  item-price-search:
    on-startup: false
    on-cron: false
    cron: 0 0 */1 * * * # every hour
    no-update-before: 12h
  inventory-search:
    on-startup: false
    on-cron: false
    cron: 0 0 */1 * * * # every hour
    no-update-before: 24h
    disable-tracking-on-empty-response: true
    delete-not-found-entities: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scmt
    username: scmt
    password: scmtsupersecret
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true