version: '3.9'

services:
  steam-community-market-tracker:
    image: ghcr.io/hypercdn/scmt:main
    container_name: steam-community-market-tracker
    restart: unless-stopped
    depends_on:
      - steam-community-market-tracker-db
    networks:
      - steam-community-market-tracker
    ports:
      - 9090:9090
    volumes:
      - ./application.yml:/WORKDIR/application.yml
  steam-community-market-tracker-db:
    image: postgres:15.2-alpine
    container_name: steam-community-market-tracker-db
    restart: unless-stopped
    networks:
      - steam-community-market-tracker
    ports:
      - 5432:5432
    volumes:
      - steam-community-market-tracker-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scmt
      - POSTGRES_USER=scmt
      - POSTGRES_PASSWORD=scmtsupersecret

volumes:
  steam-community-market-tracker-data:
    name: steam-community-market-tracker-data
networks:
  steam-community-market-tracker:
    name: steam-community-market-tracker