version: '3.9'

services:
  postgresql_scmt:
    image: postgres:15.2-alpine
    container_name: postgresql_scmt
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgressupersecret
